/**
 * Source registry.
 *
 * These are metadata records pointing at authoritative documents. The full
 * documents are NOT bundled — `sourceUrl` is the primary reference. A
 * maintainer adds a local mirror (`localPath` + `sha256`) and flips passages
 * to VERIFIED after checking them against the primary document.
 *
 * URLs are best-effort references to official publications. If a link rots,
 * the citation (title + authority + date) still lets a reader find it.
 *
 * `sourceClass` is assigned deliberately for every record — see
 * lib/sources/types.ts#canIndependentlyVerify. It is never left to a
 * heuristic. `documentNumber` is left null rather than guessed wherever
 * PostalMind does not hold the actual printed instrument number — the same
 * "never fabricate a page/order number" rule that governs citations applies
 * to this registry.
 */

import type { SourceRecord } from '@/lib/sources/types';

const NOW = '2026-09-04T00:00:00Z';

export const SOURCES: SourceRecord[] = [
  {
    id: 'gds-ce-rules-2020',
    title: 'Gramin Dak Sevaks (Conduct and Engagement) Rules, 2020',
    authority: 'Department of Posts, Ministry of Communications, Government of India',
    documentType: 'RULE',
    documentNumber: '17-30/2019-GDS',
    date: '2020-06-18',
    effectiveDate: '2020-06-18',
    supersededDate: null,
    sourceUrl: 'https://www.indiapost.gov.in/VAS/Pages/GraminDakSevaks.aspx',
    canonicalUrl: 'https://utilities.cept.gov.in/dop/pdfbind.ashx?id=4323',
    localPath: '.data/sources/original/gds-ce-rules-2020.pdf',
    localFilename: 'gds-ce-rules-2020.pdf',
    mimeType: 'application/pdf',
    sha256: '8e0a44c85dcfc1d2bf3ae59a84714dd7b7ca8f5a16ed7d2d509bfbf521f9339b',
    pageCount: 39,
    sections: ['Nature of engagement', 'Disciplinary authority and penalties'],
    status: 'VERIFIED',
    sourceClass: 'PRIMARY_OFFICIAL',
    verifiedAt: '2026-09-08T16:30:00Z',
    verificationMethod: 'manual-primary-document-check',
    verificationNotes:
      'Fetched 2026-09-08 via Playwright Chromium browser-context request (HTTP 200, application/pdf, 12854242 bytes) from official CEPT endpoint utilities.cept.gov.in/dop/pdfbind.ashx?id=4323. Magic bytes %PDF-1.3 verified; text extracted with pdf-parse. Covering OM No. 17-30/2019-GDS dated 14.02.2020 circulates the 2020 Rules in supersession of the 2011 Rules. Checked: Rule 3-A(i) 5-hour duty cap and 3-A(v) "outside the Civil Service of the Union" (doc p.3); Rules 8/9 minor+major penalties, 10-A/10-B procedures (doc pp.11-14); Rule 12 Put Off Duty (doc pp.17-20); Rule 13 appeal within three months (doc p.20+). One injection-detector flag on doc p.2 ("You are requested to ensure...") dispositioned as standard bureaucratic English false positive.',
    verifiedPages: [1, 2, 3, 11, 12, 13, 14, 17, 18, 19, 20],
    tags: ['gds', 'conduct', 'engagement', 'discipline', 'service-conditions'],
    createdAt: NOW,
    updatedAt: NOW,
    summary:
      'The principal rules governing engagement, conduct, put-off duty, disciplinary action, and service conditions of Gramin Dak Sevaks. Notified 2020, superseding the 2011 rules.',
    versions: [
      {
        versionId: 'v1_8e0a44c8',
        sourceId: 'gds-ce-rules-2020',
        sha256: '8e0a44c85dcfc1d2bf3ae59a84714dd7b7ca8f5a16ed7d2d509bfbf521f9339b',
        localFilename: 'gds-ce-rules-2020.pdf',
        mimeType: 'application/pdf',
        byteLength: 12854242,
        pages: 39,
        retrievedAt: '2026-09-08T16:16:14.617Z',
        supersedesVersionId: null,
        ingestedAt: '2026-09-08T16:30:00Z',
      },
    ],
  },
  {
    id: 'kamlesh-chandra-committee-2016',
    title: 'Report of the One-Man Committee on Gramin Dak Sevaks (Shri Kamlesh Chandra Committee)',
    authority: 'Department of Posts, Government of India',
    documentType: 'GUIDANCE_NOTE',
    documentNumber: null,
    date: '2016-11-24',
    effectiveDate: null,
    supersededDate: null,
    sourceUrl: 'https://www.indiapost.gov.in/VAS/Pages/GraminDakSevaks.aspx',
    canonicalUrl: null,
    localPath: null,
    localFilename: null,
    mimeType: null,
    sha256: null,
    pageCount: null,
    sections: ['Working hours / workload norms', 'Business development / incentives'],
    status: 'UNVERIFIED',
    sourceClass: 'PRIMARY_OFFICIAL',
    verifiedAt: null,
    verificationMethod: null,
    verificationNotes: null,
    verifiedPages: [],
    tags: ['gds', 'wages', 'trca', 'allowances', 'committee'],
    createdAt: NOW,
    updatedAt: NOW,
    summary:
      'Committee report that recommended the revised wage/TRCA structure, working-hours norms and allowances for GDS; basis for the 2018 implementation order.',
    versions: [],
  },
  {
    id: 'dop-trca-order-2018',
    title:
      'Implementation of recommendations of the GDS Committee — revised Time Related Continuity Allowance (TRCA)',
    authority: 'Department of Posts, Establishment Division',
    documentType: 'TRCA_ORDER',
    documentNumber: '17-31/2016-GDS',
    date: '2018-06-25',
    effectiveDate: '2018-07-01',
    supersededDate: null,
    sourceUrl: 'https://utilities.cept.gov.in/dop/ViewUploads.aspx?uid=10',
    canonicalUrl: 'https://utilities.cept.gov.in/dop/pdfbind.ashx?id=2936',
    localPath: '.data/sources/original/dop-trca-order-2018.pdf',
    localFilename: 'dop-trca-order-2018.pdf',
    mimeType: 'application/pdf',
    sha256: '1178455813ad585cb15d8df349bb77c2bcb17dba4b52e2dfe90c03a7ab6502b9',
    pageCount: 15,
    sections: ['Revised TRCA structure'],
    status: 'VERIFIED',
    sourceClass: 'PRIMARY_OFFICIAL',
    verifiedAt: '2026-09-08T17:15:00Z',
    verificationMethod: 'manual-primary-document-check',
    verificationNotes:
      'Discovered 2026-09-08 via official CEPT Employee Corner search (Subject=GDS, keyword "allowances") and fetched via Playwright Chromium browser-context request (HTTP 200, application/pdf, 5085090 bytes). OM No. 17-31/2016-GDS dated 25.06.2018 implements Kamlesh Chandra committee recommendations (committee set up vide Resolution 17-13/2013-GDS dated 19.11.2015, report submitted 24.11.2016). Checked: two categories (BPM / other than BPM), 4- and 5-hour slabs with two TRCA levels each, 11 old slabs merged into 3 (doc pp.1-3); DA continues per 7th CPC as separate component, revised TRCA and allowances wef 01.07.2018, arrears 01.01.2016-30.06.2018 at factor 2.57 (doc p.4).',
    verifiedPages: [1, 2, 3, 4],
    tags: ['trca', 'wages', 'gds', 'allowances', 'arrears'],
    createdAt: NOW,
    updatedAt: NOW,
    summary:
      'Directorate order implementing the revised TRCA slabs for GDS with effect from 1 July 2018, including the two-level TRCA structure and dearness allowance linkage.',
    versions: [
      {
        versionId: 'v1_11784558',
        sourceId: 'dop-trca-order-2018',
        sha256: '1178455813ad585cb15d8df349bb77c2bcb17dba4b52e2dfe90c03a7ab6502b9',
        localFilename: 'dop-trca-order-2018.pdf',
        mimeType: 'application/pdf',
        byteLength: 5085090,
        pages: 15,
        retrievedAt: '2026-09-08T16:30:04.864Z',
        supersedesVersionId: null,
        ingestedAt: '2026-09-08T17:15:00Z',
      },
    ],
  },
  {
    id: 'dop-gds-leave-instructions',
    title: 'Leave rules applicable to Gramin Dak Sevaks (consolidated instructions)',
    authority: 'Department of Posts, GDS Section',
    documentType: 'LEAVE_INSTRUCTION',
    documentNumber: '17-12/2025-GDS',
    date: '2025-12-30',
    effectiveDate: '2026-01-01',
    supersededDate: null,
    sourceUrl: 'https://utilities.cept.gov.in/dop/ViewUploads.aspx?uid=10',
    canonicalUrl: 'https://utilities.cept.gov.in/dop/pdfbind.ashx?id=14477',
    localPath: '.data/sources/original/dop-gds-leave-accumulation-2025.pdf',
    localFilename: 'dop-gds-leave-accumulation-2025.pdf',
    mimeType: 'application/pdf',
    sha256: '762f0cfb7d2493eae02c6977b544233479f4f3f21f8f9b5a9cca09b85540bb5b',
    pageCount: 4,
    sections: ['Paid leave'],
    status: 'VERIFIED',
    sourceClass: 'PRIMARY_OFFICIAL',
    verifiedAt: '2026-09-08T17:30:00Z',
    verificationMethod: 'manual-primary-document-check',
    verificationNotes:
      'Discovered 2026-09-08 via official CEPT Employee Corner search (Subject=GDS, keyword "leave") and fetched via Playwright Chromium browser-context request (HTTP 200, application/pdf, 121024 bytes). OM No. 17-12/2025-GDS dated 30.12.2025 amends Rule 7 (paid leave) of the GDS (Conduct and Engagement) Rules 2020 wef 01.01.2026: 20 days/year (10 per half-year, credited 1 Jan/1 Jul), carry-forward max 45 days, 1.67 days per completed calendar month with rounding, no encashment ever (lapse on discharge/death/cessation), combinable with maternity/LWA except emergency leave, Sundays/holidays affixable. Historical anchor cross-checked: OM No. 17-136/2001-GDS dated 24.04.2003 "Grant of paid leave" (same CEPT archive id=1568, 138045 bytes, sha256 a39a50e1..., 3-page scan read visually) — paid leave introduced vide Dte OM 17.12.1998; sanctioning authorities must not deny paid leave on combination-of-duties grounds; combination capped at 5 hours/day with combined duty allowance.',
    verifiedPages: [1, 2, 3, 4],
    tags: ['leave', 'gds', 'paid-leave', 'emergency-leave', 'maternity-leave'],
    createdAt: NOW,
    updatedAt: NOW,
    summary:
      'Consolidated departmental instructions on leave entitlement for GDS (paid leave, leave accumulation, maternity leave, leave without allowance). Individual OMs should be cited for specific entitlements.',
    versions: [
      {
        versionId: 'v1_762f0cfb',
        sourceId: 'dop-gds-leave-instructions',
        sha256: '762f0cfb7d2493eae02c6977b544233479f4f3f21f8f9b5a9cca09b85540bb5b',
        localFilename: 'dop-gds-leave-accumulation-2025.pdf',
        mimeType: 'application/pdf',
        byteLength: 121024,
        pages: 4,
        retrievedAt: '2026-09-08T16:32:29.748Z',
        supersedesVersionId: null,
        ingestedAt: '2026-09-08T17:30:00Z',
      },
    ],
  },
  {
    id: 'nsi-posb-interest-rates',
    title: 'Small Savings (POSB, RD, TD, MIS, NSC, SSA, SCSS, PPF) interest rates — quarterly notification',
    authority: 'Department of Economic Affairs (Budget Division), Ministry of Finance',
    documentType: 'FINANCIAL_PRODUCT_DOC',
    documentNumber: 'F.No.1/4/2019-NS',
    date: '2026-06-30',
    effectiveDate: '2026-07-01',
    supersededDate: null,
    sourceUrl: 'https://dea.gov.in/budget-division/revision-interest-rates-small-savings-schemes-reg',
    canonicalUrl: 'https://dea.gov.in/files/budget_division_documents/Q2ROI.pdf',
    localPath: '.data/sources/original/small-savings-q2-2026-27.pdf',
    localFilename: 'small-savings-q2-2026-27.pdf',
    mimeType: 'application/pdf',
    sha256: 'fc7b2fc03c5cf42f1c18154d75a6c2770e1a189f455473a5b2eaadf53bb7a882',
    pageCount: 1,
    sections: ['Interest rates'],
    status: 'VERIFIED',
    sourceClass: 'PRIMARY_OFFICIAL',
    verifiedAt: '2026-09-08T17:00:00Z',
    verificationMethod: 'manual-primary-document-check',
    verificationNotes:
      'Fetched 2026-09-08 via Playwright Chromium DOM discovery on the official DEA page (clicked "View" link) — HTTP 200, application/pdf, 2721982 bytes, scanned-image PDF read visually page-by-page. OM F.No.1/4/2019-NS dated 30.06.2026 (Masroor Ahmad, Deputy Secretary Budget): Q2 FY2026-27 rates (01.07.2026-30.09.2026) remain UNCHANGED from Q1 FY2026-27 — no numerical table in this OM. Chain followed: Q1 OM F.No.1/4/2019-NS dated 30.03.2026 (same signatory) likewise holds rates unchanged from Q4 FY2025-26; obtained as enclosure to DoP SB Order No. 01/2026 dated 30.03.2026 fetched from official CEPT endpoint utilities.cept.gov.in/dop/pdfbind.ashx?id=14728 (HTTP 200, 3002098 bytes, sha256 c8acc187..., 2 pages, text p.1 + enclosed memo scan p.2 read visually). No numerical rates are asserted from either OM — a rate-table quarter must still be loaded before quoting any rate.',
    verifiedPages: [1],
    tags: ['posb', 'rd', 'td', 'mis', 'nsc', 'ssa', 'ppf', 'interest-rate', 'ippb'],
    createdAt: NOW,
    updatedAt: NOW,
    summary:
      'Small savings interest rates are notified by the Ministry of Finance every quarter. Always cite the notification for the specific quarter — rates change and must never be stated from memory.',
    versions: [
      {
        versionId: 'v1_fc7b2fc0',
        sourceId: 'nsi-posb-interest-rates',
        sha256: 'fc7b2fc03c5cf42f1c18154d75a6c2770e1a189f455473a5b2eaadf53bb7a882',
        localFilename: 'small-savings-q2-2026-27.pdf',
        mimeType: 'application/pdf',
        byteLength: 2721982,
        pages: 1,
        retrievedAt: '2026-09-08T16:25:19.109Z',
        supersedesVersionId: null,
        ingestedAt: '2026-09-08T17:00:00Z',
      },
    ],
  },
  {
    id: 'rti-act-2005',
    title: 'The Right to Information Act, 2005',
    authority: 'Government of India',
    documentType: 'RULE',
    documentNumber: 'Act No. 22 of 2005',
    date: '2005-06-15',
    effectiveDate: '2005-10-12',
    supersededDate: null,
    sourceUrl: 'https://www.legislative.gov.in/document/rti-act',
    canonicalUrl:
      'https://www.legislative.gov.in/static/uploads/2025/07/2764c771f16620030038e19c505c8a39.pdf',
    localPath: '.data/sources/original/rti-act-2005.pdf',
    localFilename: 'rti-act-2005.pdf',
    mimeType: 'application/pdf',
    sha256: '0246a50b7d5a2763d0b0faf3bf49a15a8023465adfc1bd42310f0bee231ce5f3',
    pageCount: 23,
    sections: ['Application and response'],
    status: 'VERIFIED',
    sourceClass: 'PARLIAMENTARY_OFFICIAL',
    verifiedAt: '2026-09-08T16:45:00Z',
    verificationMethod: 'manual-primary-document-check',
    verificationNotes:
      'Discovered 2026-09-08 via Legislative Department CMS API (central_documents id 11604 "RTI ACT", English PDF) and fetched via Playwright Chromium browser-context request (HTTP 200, application/pdf, 398502 bytes, matches CMS filesize). Gazette of India Extraordinary reprint: assent 15.06.2005, Act No. 22 of 2005. Checked: s.6 request to CPIO/SPIO with prescribed fee (Gazette p.7); s.7(1) 30-day response, 48 hours for life/liberty, deemed refusal (Gazette p.7); s.19 first appeal within 30 days to senior officer, second appeal within 90 days to CIC/SIC (Gazette pp.15-16). A 21.1MB 40-page scan of the same Act from the same CMS (central_documents id 17936, sha256 1fc938c5...) was cross-checked as alternate mirror but has no text layer. One injection-detector flag ("provisions of this Act as appear") dispositioned as statutory-language false positive.',
    verifiedPages: [1, 2, 3, 7, 15, 16],
    tags: ['rti', 'transparency', 'application', 'first-appeal', 'fee'],
    createdAt: NOW,
    updatedAt: NOW,
    summary:
      'The RTI Act 2005 — application procedure, statutory response timelines, fee, exemptions, first appeal and second appeal to the Information Commission.',
    versions: [
      {
        versionId: 'v1_0246a50b',
        sourceId: 'rti-act-2005',
        sha256: '0246a50b7d5a2763d0b0faf3bf49a15a8023465adfc1bd42310f0bee231ce5f3',
        localFilename: 'rti-act-2005.pdf',
        mimeType: 'application/pdf',
        byteLength: 398502,
        pages: 23,
        retrievedAt: '2026-09-08T16:23:41.535Z',
        supersedesVersionId: null,
        ingestedAt: '2026-09-08T16:45:00Z',
      },
    ],
  },
  {
    id: 'demo-mela-scenario',
    title: 'DEMO: Business/Mela target pressure scenario (synthetic)',
    authority: 'PostalMind AI (illustrative only)',
    documentType: 'GUIDANCE_NOTE',
    documentNumber: null,
    date: '2026-09-04',
    effectiveDate: null,
    supersededDate: null,
    sourceUrl: null,
    canonicalUrl: null,
    localPath: null,
    localFilename: null,
    mimeType: null,
    sha256: null,
    pageCount: null,
    sections: ['Illustrative timeline'],
    status: 'DEMO',
    sourceClass: 'DEMO',
    verifiedAt: null,
    verificationMethod: null,
    verificationNotes: null,
    verifiedPages: [],
    tags: ['demo', 'mela', 'target-pressure', 'workplace'],
    createdAt: NOW,
    updatedAt: NOW,
    summary:
      'Synthetic scenario material used to demonstrate the evidence workflow. Contains no real names, messages or identifiers.',
    versions: [],
  },
];

export const SOURCE_BY_ID = new Map(SOURCES.map((s) => [s.id, s]));
